import type { NextPage } from 'next'
import Head from 'next/head'
import TopBar from '../components/TopBar'
import SideBar from '../components/SideBar'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Slack</a>
          </h1>

          <p className={styles.description}>
            Get started by{' '}
            <code className={styles.code}>creating a workspace</code>
          </p>
        </main>
      </div>
    </Layout>
  )
}

export default Home
